---
version: '2.1'
services:
  app:
    build:
      context: .
    image:   821302506864.dkr.ecr.eu-west-1.amazonaws.com/idemia-app:latest
    environment:
      APP_LISTEN_ADDRESS: '0.0.0.0'
      APP_LISTEN_PORT:    1235
    ports:
      - "1235:1235"
    healthcheck:
      test: ["CMD-SHELL", "/opt/app/healthcheck.sh"]
      interval: 3s
      timeout:  2s
      retries:  10
